### ISSUE TITLE
Resize errors

### ISSUE THREAD

**Issue by cmann1** [kxgames/glooey#10]
If a widget get's too small (eg. when resizing a window) a bunch of errors like this will be thrown out:
```
RuntimeError: Gui(id=3ac8) is only 1024x86, but its children are 233x95.
```
I feel like these aren't really necessary, and could probably be silently ignored instead of flooding the console with messages.

On a side note, is this project still active?
It looks really good but hasn't had an update in a few months.

**Comment by kalekundert** [comment]
Hmm, I'm not sure why those errors are getting spat out. I have to admit that I have only used this library with fixed-size windows myself, so probably something about resizing the window is the problem.  I'll take a look this weekend, though.  Maybe if you can post a minimal working example that would help.

The project is still active, I've just been busy with other things for the past few months, and the core library itself is pretty complete (other than bugs like this).  The things that are still on my to-do list are to write the API docs and to add some more themes.

**Comment by cmann1** [comment]
Ok this sample will even crash on start:
```python
import pyglet
import glooey


class DefaultButton(glooey.Button):
	class Base(glooey.Background):
		custom_color = '#204a87'

	class Over(glooey.Background):
		custom_color = '#3465a4'

	class Down(glooey.Background):
		custom_color = '#729fcff'

window = pyglet.window.Window(1366, 768, resizable=True, vsync=True)
gui = glooey.Gui(window)

buttons = glooey.HBox()
for i in range(0, 30):
	buttons.add(DefaultButton('Btn %i' % i))

gui.add(buttons)

pyglet.app.run()
```
Or you could reduce the number of buttons and resize the window.
I think if a container's contents are too big to fit it should either force them smaller, or just let them overlap.

**Comment by kalekundert** [comment]
Regarding the first error message you reported, that seems buggy to me because it's straight-up lying to you: it's saying that the Gui can't fit it's children, but also that the Gui is much bigger than its children.  Something has to be wrong there.  But I still haven't been able to figure out what.

Regarding the example that crashes immediately, this is expected behavior.  I just made the decision to not allow GUIs that are too small to fit all their children.  My reasons for this were:

1. I thought that allowing widgets to shrink below their "minimum" sizes would add a lot of complexity, and I figured that most games just use fixed size windows anyways, so I didn't think this complexity would be worth it.

2. I thought that shrinking widgets below their minimum size would just cause things to look wrong.  Images and text could be overlapping, some buttons might be covered such that they can't be clicked, etc.  I figured that it'd be better to let the designer know that their GUI looks wrong, so that they can redesign it accordingly, than to soldier on.

I only really have my use-cases in mind, though.  I'd like to hear more about what you're trying to achieve with a dynamically resizing GUI.  

Also, I should mention that you can get around this problem by putting the part of the GUI that's too big inside a ScrollBox widget.  Scroll boxes can be arbitrarily small, so the Gui won't complain about not being able to fit things.  If the window is big enough to fit everything, the scroll box won't do anything, but if the window is too small, the scroll box will let the user scroll around to see everything.

You could also write a custom container that rearranges it's children as necessary to make them all fit, but that would be a bigger undertaking.  (Just made harder by the fact that I haven't written the relevant documentation yet...)

**Comment by cmann1** [comment]
Ok thanks, I'll try out the scrollbox.
