### ISSUE TITLE
Problem with grid

### ISSUE THREAD

**Issue by cmann1** [kxgames/glooey#11]
I don't know if I'm doing something wrong, but I'm having a hard time getting grids to behave.
Run this code and you'll see what I mean: the gui doesn't fill the whole screen.
Scroll down to the comments I added and change the `True` to `False` - swapping the rows will fix the problem for some reason.

```python
import pyglet
import glooey


class DefaultButton(glooey.Button):
	class Base(glooey.Background):
		custom_color = '#204a87'

	class Over(glooey.Background):
		custom_color = '#3465a4'

	class Down(glooey.Background):
		custom_color = '#729fcff'


window = pyglet.window.Window(1366, 768, resizable=True, vsync=True)
gui = glooey.Gui(window)

container = glooey.Grid(1, 2)
left_panel = glooey.Grid(2, 1)
viewport = glooey.Placeholder(200, 200)
bottom_left = glooey.Placeholder()

tabs = glooey.HBox()
tabs.alignment = 'top left'
tabs.padding = 0
tabs.cell_padding = 0

for name in ['button1', 'button2', 'button3', 'button4']:
	btn = DefaultButton(name)
	tabs.add(btn)

container.alignment = 'fill'
container.set_col_width(0, 0)
container.add(0, 0, left_panel)
container.add(0, 1, viewport)

# ### With the buttons on top the gui only takes up a portion of the screen
if True:
	left_panel.set_row_height(0, 0)
	left_panel.set_row_height(1, 'expand')
	left_panel.add(0, 0, tabs)
	left_panel.add(1, 0, bottom_left)

# ### Swapping and it will fill the screen
else:
	left_panel.set_row_height(0, 'expand')
	left_panel.set_row_height(1, 0)
	left_panel.add(0, 0, bottom_left)
	left_panel.add(1, 0, tabs)

gui.add(container)

pyglet.app.run()
```

**Comment by kalekundert** [comment]
Yeah, I see what you mean.  I'm not sure what's going on right away, but I'll keep looking at it.  Sorry for the trouble you're having!

**Comment by kalekundert** [comment]
Figured it out!  Thanks for catching this, it was a really nasty bug.  I made the classic noob mistake of using mutable default arguments, which in this case was causing the dictionary keeping track of the row heights to be shared between the two grids in your example.  So when you set the height ot the first row of `left_panel` to 0, it was also setting the height of the first row of `container` to be zero.  The fix was really simple, just use `None` as a default argument rather than `{}`.  I also added a test for this case, although I think it's unlikely it'll ever come up again.
