### ISSUE TITLE
LineClock.py example does not initialize properly

### ISSUE THREAD

**Issue by acubas** [kxgames/glooey#14]
I was looking through the 'Making widgets from scraps' page and I decided to test out the `LineClock` example [(here)](http://glooey.readthedocs.io/en/latest/making_widgets_from_scratch.html) for using OpenGL with glooey by running it. It seems that it does not run properly as it is. The error comes from initializing an instance of the `LineClock` class because it tries to create `Rectangle` without a batch defined. I hard coded the the batch in the contructor of `LineClock`. It seems to have fixed that.

Also, I found that your `color` here raised an error because it has not attribute `rgb`.

```Python
color = glooey.drawing.Color.from_anything(self._color) 
colors = num_vertices * color.rgb
```

I replaced `color.rgb` with `color.tuple[:3]` which seems to work.

However, I haven't been able to figure out the latest error. It indicates that the `Rectangle` class does not have a `show` method because you used it in line 140. I can't find any signs of a `show` method in the artists file. Am I missing something? or was it forgotten?

P.S.: Great project!

**Comment by kalekundert** [comment]
Sorry to make you dig through the source trying to get a demo to work.  I think these bugs are due to discrepencies between the most recent version of the code and the 0.1.1 release (`show()` used to be called `unhide()`, to answer your specific question).  I just made a 0.1.2 release last night, so can you try `pip install --upgrade glooey` and see if that works?

**Comment by acubas** [comment]
Oh, how silly of me. Yep, it runs. I should have been mindful of your releases. Thank you for the quick reply.
