### ISSUE TITLE
Overriding a button's label no longer seems to work

### ISSUE THREAD

**Issue by PythonPr0** [kxgames/glooey#29]
Downloading the 'stylizing_widgets' tutorial to make sure that I wasn't missing anything, but even the tutorial creates this 
![image](https://user-images.githubusercontent.com/32309654/58054025-297aec80-7b51-11e9-88e5-c2f9b1036a7f.png)
Evidently overriding a button's Foreground attribute no longer seems to work.
Thanks!

**Comment by kalekundert** [comment]
Thnks for finding this.  I just refactored the Button class a week or two ago, so that must be the cause of the regression.

**Comment by kalekundert** [comment]
Can you try downloading the most recent version of glooey from Github (or doing `pip install --upgrade glooey` --- I just uploaded the most recent code to PyPI) and running the tutorial script again?  I want to be sure this isn't just some kind of version-mismatch issue.

Some background: In commit 4eacfdc7c, I changed the Button class so that rather than having `Label` and `Image` inner classes, it just has a single `Foreground` inner class.  This is more flexible, because the foreground can be any widget (or combination of widgets), while before `Label` and `Image` had to be a label and an image, respectively.  However, this did break backwards compatibility.  So it's important to make sure we're working with the same version.

Also, for me the code in the "Stylizing Widgets" tutorial still seems to work properly.  So it might help if you can post the exact code snippets that you're running.  If you know which commit of glooey you're using, that would be helpful information, too.

**Comment by PythonPr0** [comment]
You're correct, turns out I forgot to --upgrade on the pip install yesterday. I assumed that pip install would upgrade automatically but I guess not (whoops). Thank you!
