### ISSUE TITLE
Icons in Buttons are not always displayed

### ISSUE THREAD

**Issue by deponovo** [kxgames/glooey#43]
Hi. I just started working with glooey and have an inconsistency problem. I am creating a VBox filled with Buttons, each having its own icon. When I load the application sometimes all are shown (the icons) sometimes not. The ones not shown are not always the same. I posted a question on stack overflow here: https://stackoverflow.com/questions/64121480/images-on-glooey-buttons-pyglet-sometimes-drawn-sometimes-not

**Comment by kalekundert** [comment]
Thanks for posting this issue; I wouldn't have noticed your question on Stack Overflow otherwise.  I'm going to close this issue here and we can continue discussing things over there if necessary.

Also, I setup email alerts for the 'glooey' tag on Stack Overflow, so in the future I should notice questions posted there more promptly.
